#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/i2s_std.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000



#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_1
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_10

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_3
#define AUDIO_I2S_SPK_SLOT_MASK  I2S_STD_SLOT_BOTH
#define AUDIO_I2S_MIC_SLOT_MASK  I2S_STD_SLOT_LEFT



#define TOUCH_BUTTON_GPIO       GPIO_NUM_8

#define CONFIG_LCD_GC9A01_240X240
/// lcd i2c 
// #define DISPLAY_SDA_PIN GPIO_NUM_5
// #define DISPLAY_SCL_PIN GPIO_NUM_4
// #define DISPLAY_WIDTH   128
// #define DISPLAY_HEIGHT  64

// #define DISPLAY_MIRROR_X false
// #define DISPLAY_MIRROR_Y false

// GPIO_NUM_4 : RST
// GPIO_NUM_8 : booot
//GPIO_NUM_21

#define DISPLAY_BACKLIGHT_PIN   GPIO_NUM_NC
#define DISPLAY_SCLK_PIN    GPIO_NUM_9
#define DISPLAY_MOSI_PIN    GPIO_NUM_5
#define DISPLAY_CS_PIN      GPIO_NUM_0
#define DISPLAY_DC_PIN      GPIO_NUM_20
#define DISPLAY_RESET_PIN   GPIO_NUM_NC

#define DISPLAY_SPI_SCLK_HZ     (10 * 1000 * 1000)

#ifdef CONFIG_LCD_GC9A01_240X240
#define LCD_TYPE_GC9A01_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

// Analog watch appearance (RGB888). These values are converted by LVGL.
#define WATCH_HOUR_HAND_COLOR   0x2EAC74
#define WATCH_MINUTE_HAND_COLOR 0x2EAC74
#define WATCH_SECOND_HAND_COLOR 0xBFA600
#define WATCH_CENTER_COLOR      0x101010
#define WATCH_HOUR_HAND_WIDTH   10
#define WATCH_MINUTE_HAND_WIDTH 7
#define WATCH_SECOND_HAND_WIDTH 3

#endif // _BOARD_CONFIG_H_
