#include "watch_display.h"

#include "application.h"
#include "config.h"

#include <cmath>
#include <ctime>
#include <esp_log.h>


// background.h is generated by reference/gen_imge_tool/image_converter.py
// with the default array name "my_image".
#include "background.h"
#define WATCH_IMAGE_DATA my_image
#define WATCH_IMAGE_WIDTH my_image_info.width
#define WATCH_IMAGE_HEIGHT my_image_info.height
#define WATCH_IMAGE_SIZE my_image_info.data_size

namespace {
constexpr float kPi = 3.14159265358979323846f;
constexpr float kHourLength = 66.0f;
constexpr float kMinuteLength = 90.0f;
constexpr float kSecondLength = 102.0f;
constexpr float kHourTail = 12.0f;
constexpr float kMinuteTail = 15.0f;
constexpr float kSecondTail = 18.0f;
constexpr float kMinorTickInnerRadius = 108.0f;
constexpr float kMajorTickInnerRadius = 103.0f;
constexpr float kTickOuterRadius = 114.0f;
constexpr float kNumberRadius = 88.0f;

lv_image_dsc_t watch_image_dsc = {};
}

WatchDisplay::WatchDisplay(esp_lcd_panel_io_handle_t panel_io,
                           esp_lcd_panel_handle_t panel, int width, int height,
                           int offset_x, int offset_y, bool mirror_x,
                           bool mirror_y, bool swap_xy)
    : SpiLcdDisplay(panel_io, panel, width, height, offset_x, offset_y,
                    mirror_x, mirror_y, swap_xy) {
    const esp_timer_create_args_t timer_args = {
        .callback = ClockTimerCallback,
        .arg = this,
        .dispatch_method = ESP_TIMER_TASK,
        .name = "analog_clock",
        .skip_unhandled_events = true,
    };
    ESP_ERROR_CHECK(esp_timer_create(&timer_args, &clock_timer_));
}

WatchDisplay::~WatchDisplay() {
    if (clock_timer_ != nullptr) {
        esp_timer_stop(clock_timer_);
        esp_timer_delete(clock_timer_);
        clock_timer_ = nullptr;
    }
    if (clock_root_ != nullptr) {
        DisplayLockGuard lock(this);
        lv_obj_del(clock_root_);
        clock_root_ = nullptr;
    }
}

void WatchDisplay::SetupUI() {
    LcdDisplay::SetupUI();

    DisplayLockGuard lock(this);
    // Keep the objects alive because LcdDisplay still accesses them from theme
    // and preview code, but leave them permanently hidden on this board.
    if (emoji_box_ != nullptr) {
        lv_obj_add_flag(emoji_box_, LV_OBJ_FLAG_HIDDEN);
    }
    if (preview_image_ != nullptr) {
        lv_obj_add_flag(preview_image_, LV_OBJ_FLAG_HIDDEN);
    }
    LayoutTextUI();

    clock_root_ = lv_obj_create(lv_screen_active());
    lv_obj_set_size(clock_root_, width_, height_);
    lv_obj_align(clock_root_, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_pad_all(clock_root_, 0, 0);
    lv_obj_set_style_border_width(clock_root_, 0, 0);
    lv_obj_set_style_radius(clock_root_, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(clock_root_, lv_color_black(), 0);
    lv_obj_set_scrollbar_mode(clock_root_, LV_SCROLLBAR_MODE_OFF);

    watch_image_dsc.header.magic = LV_IMAGE_HEADER_MAGIC;
    watch_image_dsc.header.cf = LV_COLOR_FORMAT_RGB565;
    watch_image_dsc.header.w = WATCH_IMAGE_WIDTH;
    watch_image_dsc.header.h = WATCH_IMAGE_HEIGHT;
    watch_image_dsc.header.stride = WATCH_IMAGE_WIDTH * 2;
    watch_image_dsc.data_size = WATCH_IMAGE_SIZE;
    watch_image_dsc.data = WATCH_IMAGE_DATA;

    lv_obj_t* background = lv_image_create(clock_root_);
    lv_image_set_src(background, &watch_image_dsc);
    lv_obj_center(background);

    CreateClockFace();

    auto create_hand = [this](lv_point_precise_t (&points)[2], uint32_t color,
                              int width) {
        lv_obj_t* hand = lv_line_create(clock_root_);
        lv_line_set_points_mutable(hand, points, 2);
        lv_obj_set_style_line_color(hand, lv_color_hex(color), 0);
        lv_obj_set_style_line_width(hand, width, 0);
        lv_obj_set_style_line_rounded(hand, true, 0);
        return hand;
    };
    hour_hand_ = create_hand(hour_points_, WATCH_HOUR_HAND_COLOR,
                             WATCH_HOUR_HAND_WIDTH);
    minute_hand_ = create_hand(minute_points_, WATCH_MINUTE_HAND_COLOR,
                               WATCH_MINUTE_HAND_WIDTH);
    second_hand_ = create_hand(second_points_, WATCH_SECOND_HAND_COLOR,
                               WATCH_SECOND_HAND_WIDTH);

    center_dot_ = lv_obj_create(clock_root_);
    lv_obj_set_size(center_dot_, 10, 10);
    lv_obj_set_style_radius(center_dot_, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(center_dot_, 0, 0);
    lv_obj_set_style_bg_color(center_dot_, lv_color_hex(WATCH_CENTER_COLOR), 0);
    lv_obj_center(center_dot_);

    lv_obj_add_flag(clock_root_, LV_OBJ_FLAG_HIDDEN);
    ESP_ERROR_CHECK(esp_timer_start_periodic(clock_timer_, 1000000));
}

void WatchDisplay::CreateClockFace() {
    const int center_x = width_ / 2;
    const int center_y = height_ / 2;

    // Draw all 60 minute marks. The five-minute marks are longer and wider.
    // Point storage belongs to WatchDisplay because LVGL keeps the pointer
    // passed to lv_line_set_points_mutable().
    for (int minute = 0; minute < 60; ++minute) {
        const float angle = minute * 6.0f * kPi / 180.0f;
        const float sine = std::sin(angle);
        const float cosine = std::cos(angle);
        const bool major = (minute % 5) == 0;
        const float inner_radius =
            major ? kMajorTickInnerRadius : kMinorTickInnerRadius;

        tick_points_[minute][0].x =
            center_x + static_cast<int>(sine * inner_radius);
        tick_points_[minute][0].y =
            center_y - static_cast<int>(cosine * inner_radius);
        tick_points_[minute][1].x =
            center_x + static_cast<int>(sine * kTickOuterRadius);
        tick_points_[minute][1].y =
            center_y - static_cast<int>(cosine * kTickOuterRadius);

        lv_obj_t* tick = lv_line_create(clock_root_);
        lv_line_set_points_mutable(tick, tick_points_[minute], 2);
        lv_obj_set_style_line_color(
            tick, lv_color_hex(major ? 0xFFFFFF : 0xB8C4CC), 0);
        lv_obj_set_style_line_width(tick, major ? 3 : 1, 0);
        lv_obj_set_style_line_rounded(tick, true, 0);
    }

    // Add all hour numerals inside the tick ring. A fixed label box keeps
    // one- and two-digit values centered on the same radius.
    for (int hour = 1; hour <= 12; ++hour) {
        const float angle = hour * 30.0f * kPi / 180.0f;
        const int number_x = center_x +
            static_cast<int>(std::sin(angle) * kNumberRadius);
        const int number_y = center_y -
            static_cast<int>(std::cos(angle) * kNumberRadius);

        lv_obj_t* label = lv_label_create(clock_root_);
        lv_label_set_text_fmt(label, "%d", hour);
        lv_obj_set_size(label, 28, 20);
        lv_obj_set_pos(label, number_x - 14, number_y - 10);
        lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(label, lv_color_white(), 0);
    }
}

void WatchDisplay::SetStatus(const char* status) {
    LcdDisplay::SetStatus(status);
    {
        DisplayLockGuard lock(this);
        LayoutTextUI();
    }
    SetClockVisible(Application::GetInstance().GetDeviceState() ==
                    kDeviceStateIdle);
}

void WatchDisplay::SetChatMessage(const char* role, const char* content) {
    LcdDisplay::SetChatMessage(role, content);
    DisplayLockGuard lock(this);
    LayoutTextUI();
}

void WatchDisplay::LayoutTextUI() {
    // Use explicit geometry on this 240x240 round panel. Relative alignment
    // against LV_SIZE_CONTENT objects can be recalculated by LVGL and move the
    // text back to its original position.
    if (status_bar_ != nullptr) {
        lv_obj_set_size(status_bar_, 180, 24);
        lv_obj_set_pos(status_bar_, 5, 38);
    }
    if (status_label_ != nullptr) {
        lv_obj_set_width(status_label_, 170);
        lv_obj_align(status_label_, LV_ALIGN_CENTER, 0, 0);
    }
    if (notification_label_ != nullptr) {
        lv_obj_set_width(notification_label_, 170);
        lv_obj_align(notification_label_, LV_ALIGN_CENTER, 0, 0);
    }
    if (bottom_bar_ != nullptr) {
        lv_obj_set_width(bottom_bar_, 190);
        lv_obj_set_pos(bottom_bar_, 5, 66);
    }
    if (chat_message_label_ != nullptr) {
        lv_obj_set_width(chat_message_label_, 174);
        lv_obj_align(chat_message_label_, LV_ALIGN_CENTER, 0, 0);
    }
}

void WatchDisplay::SetEmotion(const char* emotion) {
    // Intentionally ignore emotion changes on the round watch display. Status
    // and chat text continue to be handled by the base display implementation.
    (void)emotion;
    DisplayLockGuard lock(this);
    if (gif_controller_) {
        gif_controller_->Stop();
        gif_controller_.reset();
    }
    if (emoji_label_ != nullptr) {
        lv_obj_add_flag(emoji_label_, LV_OBJ_FLAG_HIDDEN);
    }
    if (emoji_image_ != nullptr) {
        lv_obj_add_flag(emoji_image_, LV_OBJ_FLAG_HIDDEN);
    }
    if (emoji_box_ != nullptr) {
        lv_obj_add_flag(emoji_box_, LV_OBJ_FLAG_HIDDEN);
    }
}

void WatchDisplay::SetPreviewImage(std::unique_ptr<LvglImage> image) {
    // Preview images are disabled for the text-only watch UI. Let the incoming
    // image be released here and preserve valid base-class LVGL objects.
    (void)image;
    DisplayLockGuard lock(this);
    if (gif_controller_) {
        gif_controller_->Stop();
        gif_controller_.reset();
    }
    if (preview_image_ != nullptr) {
        lv_obj_add_flag(preview_image_, LV_OBJ_FLAG_HIDDEN);
    }
    if (emoji_box_ != nullptr) {
        lv_obj_add_flag(emoji_box_, LV_OBJ_FLAG_HIDDEN);
    }
}

void WatchDisplay::SetClockVisible(bool visible) {
    if (clock_root_ == nullptr) {
        return;
    }

    DisplayLockGuard lock(this);
    if (emoji_box_ != nullptr) {
        lv_obj_add_flag(emoji_box_, LV_OBJ_FLAG_HIDDEN);
    }
    lv_obj_t* normal_ui[] = {container_, top_bar_, status_bar_, content_,
                             bottom_bar_, side_bar_};
    for (lv_obj_t* object : normal_ui) {
        if (object == nullptr) {
            continue;
        }
        if (visible) {
            lv_obj_add_flag(object, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_remove_flag(object, LV_OBJ_FLAG_HIDDEN);
        }
    }

    if (visible) {
        lv_obj_remove_flag(clock_root_, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(clock_root_);
        UpdateClock();
    } else {
        lv_obj_add_flag(clock_root_, LV_OBJ_FLAG_HIDDEN);
        // Empty chat bars are hidden by LcdDisplay; do not expose one here.
        if (bottom_bar_ != nullptr && chat_message_label_ != nullptr) {
            const char* text = lv_label_get_text(chat_message_label_);
            if (text == nullptr || text[0] == '\0') {
                lv_obj_add_flag(bottom_bar_, LV_OBJ_FLAG_HIDDEN);
            }
        }
    }
}

void WatchDisplay::ClockTimerCallback(void* arg) {
    auto* display = static_cast<WatchDisplay*>(arg);
    if (Application::GetInstance().GetDeviceState() != kDeviceStateIdle) {
        return;
    }
    DisplayLockGuard lock(display);
    display->UpdateClock();
}

void WatchDisplay::UpdateHand(lv_obj_t* hand,
                              lv_point_precise_t (&points)[2], float angle,
                              float length, float tail) {
    const float sine = std::sin(angle);
    const float cosine = std::cos(angle);
    const int center_x = width_ / 2;
    const int center_y = height_ / 2;
    points[0].x = center_x - static_cast<int>(sine * tail);
    points[0].y = center_y + static_cast<int>(cosine * tail);
    points[1].x = center_x + static_cast<int>(sine * length);
    points[1].y = center_y - static_cast<int>(cosine * length);

    // The line was created while all points were still {0, 0}.  Invalidating
    // alone does not make LVGL recompute the line object's bounding box, so
    // the hand remains clipped to a zero-size area.  Setting the points again
    // refreshes both the geometry and the invalidated drawing area.
    lv_line_set_points_mutable(hand, points, 2);
}

void WatchDisplay::UpdateClock() {
    if (clock_root_ == nullptr || lv_obj_has_flag(clock_root_, LV_OBJ_FLAG_HIDDEN)) {
        return;
    }

    const time_t now = time(nullptr);
    struct tm time_info = {};
    localtime_r(&now, &time_info);
    const float hour = (time_info.tm_hour % 12) + time_info.tm_min / 60.0f;
    const float minute = time_info.tm_min + time_info.tm_sec / 60.0f;
    const float hour_angle = hour * 30.0f * kPi / 180.0f;
    const float minute_angle = minute * 6.0f * kPi / 180.0f;
    const float second_angle = time_info.tm_sec * 6.0f * kPi / 180.0f;

    UpdateHand(hour_hand_, hour_points_, hour_angle, kHourLength, kHourTail);
    UpdateHand(minute_hand_, minute_points_, minute_angle, kMinuteLength,
               kMinuteTail);
    UpdateHand(second_hand_, second_points_, second_angle, kSecondLength,
               kSecondTail);
    lv_obj_move_foreground(center_dot_);
}
